### ISSUE TITLE
New logo/icon proposal

### ISSUE THREAD

**Issue by mansya** [sooshin/android-news-app#2]
Good day sir. I am a graphic designer and i am interested in designing a logo for your good project. I will be doing it as a gift for free. I just need your permission first before I begin my design. Hoping for your positive feedback. Thanks

**Comment by sooshin** [comment]
Thank you for your proposal. Unfortunately, the app icon currently exists, and the same design app is available on the Play Store. It is difficult to make changes. I am so sorry that I can't accept your valuable suggestion.
